### ISSUE TITLE
CompositeException example

### ISSUE THREAD

**Issue by ZacSweers** [uber/RxDogTag#22]
Someone was asking about this, would be good to have an example of this in the wiki and maybe even a test

**Comment by emartynov** [comment]
We released app with RxDogTag and unfortunately, we don't see extra info for the composite exception.

**Comment by ZacSweers** [comment]
Can you provide an example snippet we could test with?

**Comment by ZacSweers** [comment]
Done in #33

**Comment by ZacSweers** [comment]
definitely still interested in a snippet if you have one @emartynov
