### ISSUE TITLE
Document current benchmark results in a wiki page

### ISSUE THREAD

**Issue by ZacSweers** [uber/RxDogTag#28]
And link it from the README

Wiki page should have raw results as well as instructions on how to run them and context around how to read them (i.e. 800% diff but then look at it in ms)

**Comment by ZacSweers** [comment]
@ShaishavGandhi this would be good for the mkdocs approach

**Comment by ShaishavGandhi** [comment]
Yup! Planning to do a draft of this soon and integrate mkdocs so we'll have a nice benchmarks page.
