### ISSUE TITLE
Error: "... only supported starting with Android N... "

### ISSUE THREAD

**Issue by EGecius** [uber/RxDogTag#52]
When trying to compile I get this error:

"Default interface methods are only supported starting with Android N (--min-api 24): io.reactivex.CompletableObserver com.uber.rxdogtag.ObserverHandler.handle(io.reactivex.Completable, io.reactivex.CompletableObserver)"

Is this expected?

My setup:
        minSdkVersion 21
        targetSdkVersion 29
        multiDexEnabled true

**Comment by ZacSweers** [comment]
RxDogTag is built targeting Java 8. If your minSdk on Android is lower than 24, you must use D8 (which can desugar default interface methods) and target/source compatibility 8.

**Comment by AlexShafir** [comment]
You probably need to highlight this in README.

**Comment by AlexShafir** [comment]
I additionally have:

`Invoke-customs are only supported starting with Android O (--min-api 26)`

**Comment by ZacSweers** [comment]
RxJava itself also requires java 8 now. D8 has existed for awhile now on Android projects needing to support older minSdks. The ecosystem has moved on, time to catch up.
