### ISSUE TITLE
1.0 Proposal

### ISSUE THREAD

**Issue by ShaishavGandhi** [uber/RxDogTag#53]
RxDogTag has had some time to incubate and we'd like to propose going 1.0. There aren't any major breaking API changes that we anticipate so we'd be planning to go to 1.0 soon. 

If you have any concerns or things you want to get added before 1.0, now is the time!

If things go fine, we plan on doing 1.0 that targets RxJava 2 and a quick 2.0 which targets RxJava 3.

**Comment by ataraxus** [comment]
Just upgraded to RxJava3 and noticed RxDogTag 0.3.0 is not compatible. I would highly appreciate the implementation of your suggestion.

**Comment by ShaishavGandhi** [comment]
1.0.0 is now out 🎊
