### ISSUE TITLE
Add performance impact stats to README

### ISSUE THREAD

**Issue by AlexShafir** [uber/RxDogTag#68]
There is no information about it in README.

I looked at android-benchmark, but it was unclear to me.

For example, it mentions guardedDelegateEnabled, which I do not see mentioned in README.

**Comment by ZacSweers** [comment]
We have a dedicated section on the project site and a short summary of the results.

![image](https://user-images.githubusercontent.com/1361086/107155387-17089e00-6946-11eb-80c9-2fc6efbf2e99.jpeg)

The benchmarks confirm that overhead isn't a concern. If it was, we would call it out in the README. The data/benchmark page is there for anyone that wants to dig in deeper on their own.
