### ISSUE TITLE
Add test for empty stacktrace in stack element tag lookup

### ISSUE THREAD

**Issue by ZacSweers** [uber/RxDogTag#7]
Should result in `StackTraceElement("Unknown", "unknown", "unknown", 0)`

**Comment by ShaishavGandhi** [comment]
Was just looking into this and this is probably not possible. The `throwable` that we analyze is created under all the DogTag*Observer and so it will never have an empty stacktrace. The only way to simulate would be to test the package-private `reportError` method.

**Comment by ZacSweers** [comment]
Cool, I'm good with closing this out for now then
