### ISSUE TITLE
How can I make a jar file of this Project?

### ISSUE THREAD

**Issue by GerrieWell** [uber/RxDogTag#72]
**Library version**:

**Repro steps or stacktrace**:

Hi, dear devloper,
    I wonder how could I make a jar file of rxdogtag. Since our workplace is offline. All dependence is jar file, including rxjava2. Is there a way to package this to jar file? I notice there are some maven dependence, like these:

```
  id 'ru.vyarus.animalsniffer'
  id 'me.champeau.gradle.jmh'
  id 'org.jetbrains.dokka'
```

What role do they play. Is it nessary package all of them to jar file?

**Comment by ZacSweers** [comment]
You can just download and save the jar from maven central. If you want to build from source I suggest you separately read more on how Gradle works
